config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root               'static_pages#top'
  get  '/about', to: 'static_pages#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def build_title(page_title = '')
    base_title = "SimpleChat ver.2"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="text-center text-secondary mt-4 mx-1">
  SimpleChat ver.2 made by ha4gu, powered by Ruby on Rails
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
    <div class="container">
      <%= link_to "SimpleChat ver.2", root_path, class: "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div id="navbarSupportedContent"
        class="collapse navbar-collapse justify-content-end">
        <div class="navbar-nav text-right text-sm-left">
          <%= link_to "このアプリについて", about_path, class: "nav-item nav-link" %>
          <%= link_to "新規登録", '#', class: "nav-item nav-link" %>
          <%= link_to "ログイン", '#', class: "nav-item nav-link" %>
        </div>
      </div> <!-- div#navbarSupportedContent -->

    </div> <!-- div.container -->
  </nav>
</header>

app/views/layouts/_meta.html.erb
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta charset="utf-8">
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <%= render 'layouts/meta' %>

    <title><%= build_title(yield(:page_title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <%= render 'layouts/footer' %>

    <%= render 'shared/active_link' %>

  </body>
</html>

app/views/shared/_active_link.html.erb
<% if !yield(:active_link).empty? %>
  <script>
    window.addEventListener('DOMContentLoaded', function(){
      var target = 'div#navbarSupportedContent a[href="<%= yield :active_link %>"]';
      var currentMenuItem = document.querySelector(target);
      currentMenuItem.classList.add('active');
    });
  </script>
<% end %>

app/views/static_pages/about.html.erb
<% provide :page_title, "このアプリについて" %>
<% provide :active_link, about_path %>

<h1 class="m-3 p-1 bg-light text-dark border-left border-primary">
  このアプリについて
</h1>

<div class="mx-4 px-2">
  <p>
    SimpleChatは、大した機能を持たない、<br>
    チャットアプリのような何かになる予定です。
  </p>
  <p>
    そしてこのページには、このアプリについての説明を<br>
    記載するところなのですが、今のところまだ<br>
    特に書く内容がありません。
  </p>
  <p>
    なのでとりあえず適当な内容で欄を埋めておきます。
  </p>
</div>

app/views/static_pages/top.html.erb
<% provide :page_title, "" %>
<% provide :active_link, "" %>

<div class="jumbotron my-3">
  <h1>SimpleChat ver.2</h1>
  <h2 class="m-4">それは、単純なチャットアプリのようなもの。</h2>
  <hr class="my-4">
  <p class="text-right font-italic">
    『SimpleChatは、大した機能も持たないチャットアプリのような何かだと思います。少なくともver.1ではそうでした。』
  </p>
  <div class="text-center mt-5">
    <%= link_to "新規登録", "#", class: "btn btn-outline-primary mx-3" %>
    または
    <%= link_to "ログイン", "#", class: "btn btn-outline-primary mx-3" %>
  </div>
</div>